# Generated by Django 4.2.9 on 2024-02-04 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("messaging", "0003_alter_chat_created_at_alter_message_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 2, 4, 16, 38, 27, 60239, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="messaging.chat"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="notifications_as_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.message",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        related_name="notifications_as_reader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
