# Generated by Django 4.2.9 on 2024-02-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notification_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 4, 19, 51, 14, 56218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
