# Generated by Django 4.2.9 on 2024-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
