# Generated by Django 4.2.9 on 2024-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pass_word",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
